# Generated by Django 2.1.8 on 2019-06-13 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll2', '0002_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='bad_count',
            field=models.IntegerField(default=0, verbose_name='差评数'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='detail',
            field=models.CharField(blank=True, default='', max_length=1023, verbose_name='详情'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='good_count',
            field=models.IntegerField(default=0, verbose_name='好评数'),
        ),
    ]
