# Generated by Django 2.1.8 on 2019-06-13 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll2', '0003_auto_20190613_1135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='good_count',
            new_name='shit',
        ),
    ]
