# Generated by Django 2.1.8 on 2019-06-13 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll2', '0004_auto_20190613_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='shit',
            new_name='good_count',
        ),
    ]
