# Generated by Django 2.1.8 on 2019-06-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll2', '0005_auto_20190613_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='photo',
            field=models.CharField(default='', max_length=1023, verbose_name='照片'),
        ),
    ]
